name: Haskell CI

on:
  - push
  - pull_request

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        enable-stack: true

    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
